version: '3'

services:
  order-service:
    build:
      context: ./../orderManagement
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1